import "./globals.css"

import Script from "next/script"
import { type Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { ConvexProvider } from "@/components/convex-provider"
import { ThemeProvider } from "@/components/theme-provider"
import { QueryProvider } from "@/components/query-provider"
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {process.env.NODE_ENV === "development" && (
        <head>
          <Script
            crossOrigin="anonymous"
            src="//unpkg.com/react-scan/dist/auto.global.js"
          />
        </head>
      )}

      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider>
          <ConvexProvider>
            <QueryProvider>
              <TooltipProvider>
                <Toaster />
                <div vaul-drawer-wrapper="" className="bg-background">
                  {children}
                </div>
              </TooltipProvider>
            </QueryProvider>
          </ConvexProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
